// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for UnauthorizedRoleAccessCanaryFunction
 */
export interface UnauthorizedRoleAccessCanaryFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/canaries/unauthorized-role-access/unauthorized-role-access.canary.
 */
export class UnauthorizedRoleAccessCanaryFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: UnauthorizedRoleAccessCanaryFunctionProps) {
    super(scope, id, {
      description: 'src/canaries/unauthorized-role-access/unauthorized-role-access.canary.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/canaries/unauthorized-role-access/unauthorized-role-access.canary.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}