// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for DirtyEnvironmentsWidgetFunction
 */
export interface DirtyEnvironmentsWidgetFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/dashboards/custom-widgets/dirty-environments/dirty-environments.widget.
 */
export class DirtyEnvironmentsWidgetFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: DirtyEnvironmentsWidgetFunctionProps) {
    super(scope, id, {
      description: 'src/dashboards/custom-widgets/dirty-environments/dirty-environments.widget.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../../assets/dashboards/custom-widgets/dirty-environments/dirty-environments.widget.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}