// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for CleanupTimeoutFunction
 */
export interface CleanupTimeoutFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/cleanup-timeout/cleanup-timeout.
 */
export class CleanupTimeoutFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: CleanupTimeoutFunctionProps) {
    super(scope, id, {
      description: 'src/cleanup-timeout/cleanup-timeout.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/cleanup-timeout/cleanup-timeout.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}