// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for DeallocateFunction
 */
export interface DeallocateFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/deallocate/deallocate.
 */
export class DeallocateFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: DeallocateFunctionProps) {
    super(scope, id, {
      description: 'src/deallocate/deallocate.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/deallocate/deallocate.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}