/**
 * Environment variable names.
 */
export const env = {
  ALLOCATIONS_TABLE_NAME_ENV: 'CDK_ATMOSPHERE_ALLOCATIONS_TABLE_NAME',
  ENVIRONMENTS_TABLE_NAME_ENV: 'CDK_ATMOSPHERE_ENVIRONMENTS_TABLE_NAME',
  CONFIGURATION_BUCKET_ENV: 'CDK_ATMOSPHERE_CONFIGURATION_FILE_BUCKET',
  CONFIGURATION_KEY_ENV: 'CDK_ATMOSPHERE_CONFIGURATION_FILE_KEY',
};